name: Linting

on:
  pull_request:
  push:
    paths:
      - .github/workflows/lint.yml
      - scripts/**

jobs:
  executable-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test if scripts are executable
        run: |
          n=0
          for f in scripts/*; do
            [ "$f" != scripts/lib.sh ] || continue
            if [ -f "$f" ] && [ ! -x "$f" ]; then
              printf "'%s' is not executable\n" "$f" >&2
              n=1
            fi
          done
          exit $n

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: scripts